### ISSUE TITLE
Trying to understand why failing to build on binder

### ISSUE THREAD

**Issue by Analect** [NHDaly/jupyter-binder#2]
@NHDaly 
Thanks for this example repo. I came across it while reviewing some of the issues in the binder repo and was trying to get it up and running ... but it seems to fail to generate the image on step 26 and given I'm trying to get a better handle on binder, I wanted to try to better understand what types of issues can lead to a failed build for an image.  What is going wrong here?  Did it fail to install something on an earlier step .. and is now erroring-out because of that?  Are there any mechanisms in place within binder to alert to a repo owner when there's a build failure like this?

Thanks.

```
Step 26 : RUN ln ffmpeg-3.1.2-64bit-static/ffmpeg /usr/local/bin/ffmpeg
---> Running in 13074ee81587
[91mln: failed to access ‘ffmpeg-3.1.2-64bit-static/ffmpeg’: No such file or directory[0m
could not build image nhdaly-jupyter-binder: Error: build failed for imageName: nhdaly-jupyter-binder
registering template for nhdaly-jupyter-binder
```

**Comment by psychemedia** [comment]
The Dockerfile gets `ffmpeg-release-64bit-static.tar.xz` and then tries to link `ffmpeg-3.1.2-64bit-static/ffmpeg` but the release has moved on - it's currently `ffmpeg-3.2-64bit-static`.

**Comment by Analect** [comment]
Thanks for the info @psychemedia 
I'll close this out.

**Comment by NHDaly** [comment]
Wow, thanks @psychemedia. I guess i haven't tried to build an image in a little while.

... Is there a better ffmpeg rule i should be using that could be more generic so it won't break when they update versions, or is explicit versioning sort of the point of docker?

**Comment by psychemedia** [comment]
@NHDaly I think a strict interpretation of containers would be that you version images with particular contents: when you are happy with an image (eg built with baked package application numbers inside to be even more explicit) you freeze it; as you update contents, you can rebuild and update the image version number.

Re: a generic rule, I guess you could download the latest package and detect the ffmpeg version from the filename.

I think `tar -tf filename.tar.gz` will give you the names of the files in archive that you could use in the linker like?
